### ISSUE TITLE
Color nick won't work with non op player when "use-permissions: false"

### ISSUE THREAD

**Issue by Charon-3** [Majekdor/HexNicks#7] opened 2021-06-25 19:55 UTC
Step to reproduce.
1. Install plugin.
2. Start the server with default Settings and no permission manager plugin.
3. Non op player use `/nick <gradient:#00ff00:#ff0000>UserName</gradient>`
4. The plugins register player username as `<gradient:#00ff00:#ff0000>UserName</gradient>` instead of `UserName` in color.
![image](https://user-images.githubusercontent.com/19683257/123478502-babec600-d629-11eb-81b5-989454b5c5e7.png)

**Comment by Majekdor** [comment] 2021-06-25 21:17
Okay, so the issue is that the permission you need isn't being given by default. I have a permissions refactor in the works that will fix this. It's actually intentional to have it appear not formatted if you don't have the right perms though.

**Comment by Majekdor** [comment] 2021-06-25 21:26
Fixed in latest [release](https://github.com/Majekdor/HexNicks/releases/tag/v1.4.4).

**Closed by Majekdor** 2021-06-25 21:26 UTC
